#!/usr/bin/env bash
#Display To infinity nd beyond indefinitely
#+ with a sleep 2 in between each iteration
#Display I am invincible!!!, in between each iteration stopped

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done 
